### ISSUE TITLE
Fix genetic optimization in master-slave mode

### ISSUE THREAD

**Issue by ajkxyz** [Samsung/veles#28]
Launch master first:
python3 -m veles -p '' -s --optimize 25 -l 0.0.0.0:10000 veles/samples/genetics.py -
In another console launch slave:
python3 -m veles -p '' -s --optimize 25 -m localhost:10000 veles/samples/genetics.py -

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [1](https://velesnet.ml/gerrit/#/c/134/1)
for change [134](https://velesnet.ml/gerrit/#/c/134) which triggered build [2256](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Veles/2256/)

**Comment by ajkxyz** [comment]
Sometimes slave gives an error:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/export/home/ajk/Projects/Veles/veles/txzmq/connection.py", line 371, in doRead
    message = self._readMultipart(unpickler)
  File "/export/home/ajk/Projects/Veles/veles/txzmq/connection.py", line 271, in _readMultipart
    obj = pickle.load(obj)
builtins.EOFError:
